#!/usr/bin/env bash
# diff-bundles.sh -- normalized diff between two esbuild-emitted plugin bundles.
#
# Usage:
#   bash tools/diff-bundles.sh <reference.js> <candidate.js>
#
# Example:
#   bash tools/diff-bundles.sh tools/inputs/main-v1.0.19.js main.js
#
# What it does:
#   1. Strips the leading esbuild banner comment ("THIS IS A GENERATED/BUNDLED FILE...").
#   2. Strips the runtime-helpers preamble that esbuild emits at the top of every
#      bundle (everything from `var __create = Object.create;` through the line
#      `var __toCommonJS = ...`). These helper definitions can shift between
#      esbuild versions or builds even when the input source is identical.
#   3. "Sorts" top-level `var require_<name> = __commonJS(...)` declarations.
#      In our bundles there is only ONE such wrapper (RecordRTC, a vendored CJS
#      module). If more vendored CJS modules are added later, ordering can drift.
#      Tradeoff note: a fully correct implementation extracts each multi-line
#      `var require_<name> = __commonJS({...});` block as one unit and sorts by
#      name. Doing that in pure POSIX shell is awkward; we instead rely on the
#      fact that our current bundle has a single wrapper, so a no-op sort pass
#      is correct. If future bundles add more wrappers, replace this section
#      with a Node/awk-based block extractor.
#   4. Runs `diff -u` on the two normalized streams (writes raw output to
#      tools/diff-output.patch).
#   5. Runs an order-insensitive content check via `comm` on sorted unique
#      lines. This is the *real* gate against missing/added code, since
#      esbuild can emit modules in different positions across builds. The
#      positional diff is dominated by reordering noise even when the bundles
#      are functionally identical.
#   6. Categorizes the order-insensitive deltas into buckets via successive
#      `grep -vE` filters:
#        - helper-noise:    references to esbuild helper names (__defProp etc.)
#        - module-ordering: `// src/...` or `// node_modules/...` header lines
#        - import-rename:   import_obsidianN renumbering (benign)
#        - enum-emit-form:  TypeScript const-enum emit-form differences
#                           (`"x" /* Name */` vs `"x"` plus separate comment)
#        - optional-chain-emit: `x == null ? void 0 : x.y` vs `x && x.y`
#        - id-rename:       numeric-suffix scope-clash renames (e.g.,
#                           cancelAnimationFrame -> cancelAnimationFrame2)
#        - actual-logic:    everything else; the triage queue.
#      Writes the residual "actual-logic" lines to
#      tools/diff-output.actual-logic.txt for inspection.
#
# Idempotent: re-running overwrites tools/diff-output.patch and
# tools/diff-output.actual-logic.txt.

set -euo pipefail

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <reference.js> <candidate.js>" >&2
  exit 2
fi

REF="$1"
CAND="$2"

if [ ! -f "$REF" ]; then
  echo "Reference bundle not found: $REF" >&2
  exit 2
fi
if [ ! -f "$CAND" ]; then
  echo "Candidate bundle not found: $CAND" >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIFF="${SCRIPT_DIR}/diff-output.patch"
OUT_LOGIC="${SCRIPT_DIR}/diff-output.actual-logic.txt"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

normalize() {
  local in="$1"
  local out="$2"
  awk '
    BEGIN { banner_done = 0; in_helpers = 0 }
    !banner_done {
      if ($0 ~ /^\*\/$/) { banner_done = 1; next }
      next
    }
    !in_helpers && $0 ~ /^var __create = Object\.create;/ { in_helpers = 1; next }
    in_helpers {
      if ($0 ~ /^var __toCommonJS = /) { in_helpers = 0; next }
      next
    }
    { print }
  ' "$in" > "$out"
}

NREF="${TMP_DIR}/ref.norm.js"
NCAND="${TMP_DIR}/cand.norm.js"

normalize "$REF" "$NREF"
normalize "$CAND" "$NCAND"

set +e
diff -u "$NREF" "$NCAND" > "$OUT_DIFF"
DIFF_RC=$?
set -e
if [ "$DIFF_RC" -gt 1 ]; then
  echo "diff exited with error code $DIFF_RC" >&2
  exit "$DIFF_RC"
fi

ONLY_REF="${TMP_DIR}/only-in-ref.txt"
ONLY_CAND="${TMP_DIR}/only-in-cand.txt"
sort -u "$NREF" > "${TMP_DIR}/ref.sorted.txt"
sort -u "$NCAND" > "${TMP_DIR}/cand.sorted.txt"
comm -23 "${TMP_DIR}/ref.sorted.txt" "${TMP_DIR}/cand.sorted.txt" > "$ONLY_REF"
comm -13 "${TMP_DIR}/ref.sorted.txt" "${TMP_DIR}/cand.sorted.txt" > "$ONLY_CAND"

count_lines() { wc -l < "$1" | tr -d ' '; }

ONLY_REF_TOTAL=$(count_lines "$ONLY_REF")
ONLY_CAND_TOTAL=$(count_lines "$ONLY_CAND")

# Categorization patterns (POSIX ERE, no PCRE-only constructs).
HELPER_RE='__(defProp|commonJS|toESM|toCommonJS|publicField|copyProps|export|create|getOwnPropDesc|getOwnPropNames|getProtoOf|hasOwnProp|defNormalProp|accessCheck|privateGet|privateAdd|privateSet|init[0-9]+)'
MODULE_RE='^[[:space:]]*//[[:space:]]*(src|src-rebuild|node_modules)/'
IMPORT_RENAME_RE='import_(obsidian|meta)[0-9]*'
ENUM_EMIT_RE='^[[:space:]]*("(deepgram|groq|openai|low|medium|high)"[[:space:],]*$|/\*[[:space:]](Deepgram|Groq|OpenAI|Low|Medium|High)[[:space:]]\*/[[:space:],]*$)'
# Optional-chain emit: ref form `== null ? void 0 :` and rebuilt form `&& <ident>.<ident>`
OPT_CHAIN_RE='(== null \? void 0 :|&&[[:space:]]+[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_])'
# Numeric-suffix renames (e.g. `cancelAnimationFrame2 = ...`) at any indent.
ID_RENAME_RE='[A-Za-z_][A-Za-z0-9_]*[0-9]+[[:space:]]*='

bucketize() {
  # $1 = input file ; emits "helper:N module:N import:N enum:N optchain:N idren:N logic:N"
  local in="$1"
  local total
  total=$(count_lines "$in")

  local h m i e o r logic
  h=$(grep -cE "$HELPER_RE" "$in" || true)
  # Strip helper hits, then bucket the rest in priority order.
  local f1="${TMP_DIR}/$(basename "$in").no-helper"
  grep -vE "$HELPER_RE" "$in" > "$f1" || true

  m=$(grep -cE "$MODULE_RE" "$f1" || true)
  local f2="${TMP_DIR}/$(basename "$in").no-module"
  grep -vE "$MODULE_RE" "$f1" > "$f2" || true

  i=$(grep -cE "$IMPORT_RENAME_RE" "$f2" || true)
  local f3="${TMP_DIR}/$(basename "$in").no-import"
  grep -vE "$IMPORT_RENAME_RE" "$f2" > "$f3" || true

  e=$(grep -cE "$ENUM_EMIT_RE" "$f3" || true)
  local f4="${TMP_DIR}/$(basename "$in").no-enum"
  grep -vE "$ENUM_EMIT_RE" "$f3" > "$f4" || true

  o=$(grep -cE "$OPT_CHAIN_RE" "$f4" || true)
  local f5="${TMP_DIR}/$(basename "$in").no-optchain"
  grep -vE "$OPT_CHAIN_RE" "$f4" > "$f5" || true

  r=$(grep -cE "$ID_RENAME_RE" "$f5" || true)
  local f6="${TMP_DIR}/$(basename "$in").no-idren"
  grep -vE "$ID_RENAME_RE" "$f5" > "$f6" || true

  logic=$(count_lines "$f6")
  echo "$h $m $i $e $o $r $logic"
  # Side-effect: write the residual file path to a fixed sentinel for caller.
  printf "%s" "$f6" > "${TMP_DIR}/last-residual.path"
}

# Reset the actual-logic output file.
: > "$OUT_LOGIC"

echo "diff-bundles.sh summary"
echo "  reference: $REF"
echo "  candidate: $CAND"
echo "  raw diff:  $OUT_DIFF"
echo
LINEAR=$(awk '/^---/||/^\+\+\+/{next} /^[+-]/{c++} END{print c+0}' "$OUT_DIFF")
echo "Linear (positional) diff:"
echo "  +/- payload lines: $LINEAR"
echo "  Note: positional diff is dominated by esbuild module-reordering;"
echo "  treat order-insensitive content delta below as the real signal."
echo
echo "Order-insensitive content delta:"
echo "  unique lines only in reference: $ONLY_REF_TOTAL"
echo "  unique lines only in candidate: $ONLY_CAND_TOTAL"
echo

printf "Categorization (only-in-ref):\n"
read -r RH RM RI RE RO RR RL <<<"$(bucketize "$ONLY_REF")"
printf "  helper:%s  module-ord:%s  import-rename:%s  enum-emit:%s  opt-chain:%s  id-rename:%s  actual-logic:%s\n" "$RH" "$RM" "$RI" "$RE" "$RO" "$RR" "$RL"
echo "## ONLY-IN-REFERENCE actual-logic residue ($RL lines)" >> "$OUT_LOGIC"
cat "$(cat "${TMP_DIR}/last-residual.path")" >> "$OUT_LOGIC"
echo "" >> "$OUT_LOGIC"

printf "Categorization (only-in-candidate):\n"
read -r CH CM CI CE CO CR CL <<<"$(bucketize "$ONLY_CAND")"
printf "  helper:%s  module-ord:%s  import-rename:%s  enum-emit:%s  opt-chain:%s  id-rename:%s  actual-logic:%s\n" "$CH" "$CM" "$CI" "$CE" "$CO" "$CR" "$CL"
echo "## ONLY-IN-CANDIDATE actual-logic residue ($CL lines)" >> "$OUT_LOGIC"
cat "$(cat "${TMP_DIR}/last-residual.path")" >> "$OUT_LOGIC"

TOTAL_RESIDUAL=$(( RL + CL ))

echo
echo "Residual 'actual-logic' lines written to: $OUT_LOGIC"
echo "  total residual: $TOTAL_RESIDUAL"
if [ "$TOTAL_RESIDUAL" -gt 0 ]; then
  echo
  echo "First 80 residual lines:"
  head -80 "$OUT_LOGIC" | sed 's/^/  /'
fi

echo
echo "Done."
